### PR TITLE
Add jars management via maven & logstash 2 support

### PR DESCRIPTION
**Pull request by salekseev**

### CODE REVIEW

**Comment by avishai-ish-shalom** [comment]
I can't accept this PR as is because it changes the license, if you want me to change the license please give a compelling reason to do so.

**Comment by salekseev** [comment]
Sorry, didn't even realize those had different licenses as all the rest of logstash plugins have Apache license. I'm not a lawyer but let me dig in to see if I can relicense APL code into GPL...

**Comment by avishai-ish-shalom** [comment]
This plugin is LGPL licensed. Why do you need to re-license? do you have to copy paste code from elsewhere?

**Comment by avishai-ish-shalom** [comment]
@salekseev I'm willing to change the license to conform with the majority of Logstash plugins. I can't live with the copy-and-paste from logstash skeleton plugin. E.g. the contributors file and README are completely wrong. Would you mind fixing the PR? if not, lmk.

**Comment by salekseev** [comment]
I'll try to find some time this weekend to pretty it up. Thanks a bunch.

**Comment by salekseev** [comment]
Sorry, I've lost interest in this.

**Pull request closed without merging**
